-- ProxyPoker account schema
-- Run this entire file once in the Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text check (char_length(display_name) between 1 and 12),
  tutorial_hands integer not null default 0 check (tutorial_hands >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.poker_hands (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  mode text not null check (mode in ('solo', 'multiplayer')),
  result text not null check (result in ('win', 'loss', 'tie')),
  opponent text check (char_length(opponent) <= 80),
  finish_type text not null check (finish_type in ('fold', 'showdown')),
  final_stack integer,
  played_at timestamptz not null default now()
);

create index if not exists poker_hands_user_played_at_idx
  on public.poker_hands (user_id, played_at desc);

alter table public.profiles enable row level security;
alter table public.poker_hands enable row level security;

-- New tables are not automatically exposed to Data API roles in this project.
-- Grant only the operations the signed-in browser client actually uses; RLS
-- below still limits every operation to the authenticated player's own rows.
grant usage on schema public to authenticated;
grant select, insert, update on table public.profiles to authenticated;
grant select, insert on table public.poker_hands to authenticated;
grant usage, select on sequence public.poker_hands_id_seq to authenticated;

drop policy if exists "Players can read their profile" on public.profiles;
create policy "Players can read their profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Players can update their profile" on public.profiles;
create policy "Players can update their profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Players can insert their profile" on public.profiles;
create policy "Players can insert their profile"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "Players can read their hands" on public.poker_hands;
create policy "Players can read their hands"
  on public.poker_hands for select
  using (auth.uid() = user_id);

drop policy if exists "Players can insert their hands" on public.poker_hands;
create policy "Players can insert their hands"
  on public.poker_hands for insert
  with check (auth.uid() = user_id);

create or replace function public.handle_new_proxy_poker_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    left(coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1), 'Player'), 12)
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_proxy_poker_user_created on auth.users;
create trigger on_proxy_poker_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_proxy_poker_user();

create or replace function public.increment_my_tutorial_hands()
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  updated_total integer;
begin
  update public.profiles
  set tutorial_hands = tutorial_hands + 1,
      updated_at = now()
  where id = auth.uid()
  returning tutorial_hands into updated_total;
  return updated_total;
end;
$$;

revoke all on function public.increment_my_tutorial_hands() from public;
grant execute on function public.increment_my_tutorial_hands() to authenticated;
